print("hello world")
name = input("what is your name: ")
age = input("what is your age: ")
location = input("what is your location: ")
print(f"hello {name} you are {age} years old and you stay at {location}")